spring:
  profiles:
    active: development
---
server:
  port: 8080
  contextPath: /uaa
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
spring:
  profiles: development
  thymeleaf:
    cache: false
