spring:
  profiles:
    active: development
---
server:
  port: 8181
  contextPath: /uaa
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: dbpass
    initialize: true
  thymeleaf:
    cache: false
logging.level.org.springframework.security: DEBUG
