spring:
  profiles:
    active: development
---
server:
  port: 8181
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/uaa/userinfo
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: dbpass
    initialize: true
  thymeleaf:
    cache: false
